<a href="https://colab.research.google.com/github/Fei-Q/dsst389/blob/main/nb/notebook19a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Notebook19a

In [1]:
! wget -q -nc https://raw.githubusercontent.com/taylor-arnold/fds-py/refs/heads/main/funs.py

In [2]:

import numpy as np
import polars as pl

from funs import *
from plotnine import *
from polars import col as c
theme_set(theme_minimal())
pl.Config.set_fmt_str_lengths(1000)

ub = "https://raw.githubusercontent.com/taylor-arnold/fds-py-nb/refs/heads/main/"

### Small Example

Much of the code itself is already included in this notebook. We are going to go through it slowly and intentionally to understand how to parse text annotations in Python. To start, load the small English spaCy model:

In [3]:
import spacy
nlp = spacy.load("en_core_web_sm")

Next, create a corpus object with a single text. I've filled in one example, but you should use the string that you had for homework.

In [4]:
docs = pl.DataFrame({
    "doc_id": "Example",
    "text": "All human wisdom is contained in these two words—'Wait and hope.'"
})

Now parse the text with the NLP model.

In [5]:
anno = DSText.process(docs, nlp)
print_rows(anno)

shape: (13, 15)
┌─────────┬─────┬─────┬─────────────┬───┬───────────┬──────────┬──────────┬─────────┐
│ doc_id  ┆ sid ┆ tid ┆ token       ┆ … ┆ dep       ┆ head_idx ┆ ent_type ┆ ent_iob │
│ ---     ┆ --- ┆ --- ┆ ---         ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---     │
│ str     ┆ i64 ┆ i64 ┆ str         ┆   ┆ str       ┆ i64      ┆ str      ┆ str     │
╞═════════╪═════╪═════╪═════════════╪═══╪═══════════╪══════════╪══════════╪═════════╡
│ Example ┆ 1   ┆ 1   ┆ All         ┆ … ┆ det       ┆ 3        ┆          ┆ O       │
│ Example ┆ 1   ┆ 2   ┆ human       ┆ … ┆ amod      ┆ 3        ┆          ┆ O       │
│ Example ┆ 1   ┆ 3   ┆ wisdom      ┆ … ┆ nsubjpass ┆ 5        ┆          ┆ O       │
│ Example ┆ 1   ┆ 4   ┆ is          ┆ … ┆ auxpass   ┆ 5        ┆          ┆ O       │
│ Example ┆ 1   ┆ 5   ┆ contained   ┆ … ┆ ROOT      ┆ 5        ┆          ┆ O       │
│ Example ┆ 1   ┆ 6   ┆ in          ┆ … ┆ prep      ┆ 5        ┆          ┆ O       │
│ Example ┆ 1   ┆ 7   ┆ these       ┆ … ┆ det       ┆ 9        ┆          ┆ O       │
│ Example ┆ 1   ┆ 8   ┆ two         ┆ … ┆ nummod    ┆ 9        ┆ CARDINAL ┆ B       │
│ Example ┆ 1   ┆ 9   ┆ words—'Wait ┆ … ┆ pobj      ┆ 6        ┆          ┆ O       │
│ Example ┆ 1   ┆ 10  ┆ and         ┆ … ┆ cc        ┆ 9        ┆          ┆ O       │
│ Example ┆ 1   ┆ 11  ┆ hope        ┆ … ┆ conj      ┆ 9        ┆          ┆ O       │
│ Example ┆ 1   ┆ 12  ┆ .           ┆ … ┆ punct     ┆ 5        ┆          ┆ O       │
│ Example ┆ 1   ┆ 13  ┆ '           ┆ … ┆ punct     ┆ 5        ┆          ┆ O       │
└─────────┴─────┴─────┴─────────────┴───┴───────────┴──────────┴──────────┴─────────┘

Compare this to what you did for the homework. Are there any differences?

### Grabbing Some Data

Next, we are going to grab some text data from Wikipedia. I've written a script that called the Wikipedia API to get the text from a page. Here is the function that takes a page name and returns the text.

In [6]:
import re
import requests
from lxml import html

def wiki_get_text(page):
    resp = requests.get(
        "https://en.wikipedia.org/w/api.php",
        params={
            "action": "parse",
            "page": page,
            "prop": "text",
            "format": "json",
        },
        headers={"User-Agent": "MyBot/1.0 (myemail@example.com)"},
    )
    raw_html = resp.json()["parse"]["text"]["*"]
    tree = html.fromstring(raw_html)
    text = " ".join(p.text_content().strip() for p in tree.xpath("//p"))
    text = re.sub(r"\[\d+\]", "", text)

    return text

We can use this inside of a call to `pl.DataFrame` to build a textual corpus object. Here is an example for the data science page. Start with this one and then come back with your own example.

In [21]:
df = pl.DataFrame({
    "doc_id": "Parnassius_hunnyngtoni",
    "text": wiki_get_text("Parnassius_hunnyngtoni")
})
df

shape: (1, 2)
┌────────────────────────┬─────────────────────────────────────────────────────────────────────────┐
│ doc_id                 ┆ text                                                                    │
│ ---                    ┆ ---                                                                     │
│ str                    ┆ str                                                                     │
╞════════════════════════╪═════════════════════════════════════════════════════════════════════════╡
│ Parnassius_hunnyngtoni ┆ Parnassius hunnyngtoni, the Hannyngton's Apollo, is a high-altitude     │
│                        ┆ butterfly which is found in India. It is a member of the snow Apollo    │
│                        ┆ genus (Parnassius) of the swallowtail family (Papilionidae). Some       │
│                        ┆ sources also spell the name as P. hunnygtoni. It is named after Frank   │
│                        ┆ Hannyngton who obtained the specimen from the Chumbi Valley. Northern   │
│                        ┆ slope of central Himalaya (Tibet). Previously known from the Chumbi     │
│                        ┆ Valley, northern part of India (Sikkim) which currently is occupied by  │
│                        ┆ China. It may be in Bhutan. Original description by Andrey Avinoff: I   │
│                        ┆ received this wonderful new species through the kindness of Mr.         │
│                        ┆ Hunnyngton, in honour of whom I have named this minute Parnassius. It   │
│                        ┆ comes from high elevations near the Chumbi Valley, South Tibet.         │
│                        ┆ Apparently this new species belongs to the acco-group, as may be seen   │
│                        ┆ by the corneous bag sphragis of the female and the characteristic white │
│                        ┆ scaled veins of the slightly pinkish surface of the underside of the    │
│                        ┆ secondaries. Their pattern is very pec…                                 │
└────────────────────────┴─────────────────────────────────────────────────────────────────────────┘

Once you have the data, you can process it with the NLP annotation:

In [22]:
anno = DSText.process(df, nlp)
anno

shape: (721, 15)
┌────────────────────────┬─────┬─────┬─────────────┬───┬──────────┬──────────┬──────────┬─────────┐
│ doc_id                 ┆ sid ┆ tid ┆ token       ┆ … ┆ dep      ┆ head_idx ┆ ent_type ┆ ent_iob │
│ ---                    ┆ --- ┆ --- ┆ ---         ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---     │
│ str                    ┆ i64 ┆ i64 ┆ str         ┆   ┆ str      ┆ i64      ┆ str      ┆ str     │
╞════════════════════════╪═════╪═════╪═════════════╪═══╪══════════╪══════════╪══════════╪═════════╡
│ Parnassius_hunnyngtoni ┆ 1   ┆ 1   ┆             ┆ … ┆ dep      ┆ 2        ┆          ┆ O       │
│ Parnassius_hunnyngtoni ┆ 1   ┆ 2   ┆ Parnassius  ┆ … ┆ compound ┆ 3        ┆          ┆ O       │
│ Parnassius_hunnyngtoni ┆ 1   ┆ 3   ┆ hunnyngtoni ┆ … ┆ nsubj    ┆ 10       ┆          ┆ O       │
│ Parnassius_hunnyngtoni ┆ 1   ┆ 4   ┆ ,           ┆ … ┆ punct    ┆ 3        ┆          ┆ O       │
│ Parnassius_hunnyngtoni ┆ 1   ┆ 5   ┆ the         ┆ … ┆ det      ┆ 6        ┆          ┆ O       │
│ …                      ┆ …   ┆ …   ┆ …           ┆ … ┆ …        ┆ …        ┆ …        ┆ …       │
│ Parnassius_hunnyngtoni ┆ 38  ┆ 9   ┆ by          ┆ … ┆ agent    ┆ 8        ┆          ┆ O       │
│ Parnassius_hunnyngtoni ┆ 38  ┆ 10  ┆ law         ┆ … ┆ pobj     ┆ 9        ┆          ┆ O       │
│ Parnassius_hunnyngtoni ┆ 38  ┆ 11  ┆ in          ┆ … ┆ prep     ┆ 8        ┆          ┆ O       │
│ Parnassius_hunnyngtoni ┆ 38  ┆ 12  ┆ India       ┆ … ┆ pobj     ┆ 11       ┆ GPE      ┆ B       │
│ Parnassius_hunnyngtoni ┆ 38  ┆ 13  ┆ .           ┆ … ┆ punct    ┆ 3        ┆          ┆ O       │
└────────────────────────┴─────┴─────┴─────────────┴───┴──────────┴──────────┴──────────┴─────────┘

1. Now, for a little work on your end. Using the code that was in the book, find the top 10 most common nouns on the page.

In [23]:
(
    anno
    .filter(c.upos == "NOUN")
    .group_by(c.lemma)
    .agg(count = pl.len())
    .sort(by = "count", descending = True)
    .head(10)
)

shape: (10, 2)
┌──────────┬───────┐
│ lemma    ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ marking  ┆ 9     │
│ specie   ┆ 7     │
│ spelling ┆ 5     │
│ basal    ┆ 4     │
│ name     ┆ 4     │
│ band     ┆ 4     │
│ female   ┆ 4     │
│ surface  ┆ 3     │
│ acco     ┆ 3     │
│ wing     ┆ 3     │
└──────────┴───────┘

2. And then find the top ten common adjectives.

In [24]:
(
    anno
    .filter(c.upos == "ADJ")
    .group_by(c.lemma)
    .agg(count = pl.len())
    .sort(by = "count", descending = True)
    .head(10)
)

shape: (10, 2)
┌──────────┬───────┐
│ lemma    ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ dark     ┆ 8     │
│ red      ┆ 3     │
│ original ┆ 3     │
│ curved   ┆ 3     │
│ central  ┆ 3     │
│ high     ┆ 2     │
│ black    ┆ 2     │
│ such     ┆ 2     │
│ latter   ┆ 2     │
│ corneous ┆ 2     │
└──────────┴───────┘

Go back and choose another page and see how the outputs change. Then, wait for use to come together for the next step.

### Sheets

Next we are going to create a class dataset. Once that is finished, we will use the code below to read it in.

In [25]:
SHEET_ID = "1yyeOB8AcNvoDhSoMbjEEkaKKw6REXLV-mH4oJpg0qB8"
GID = "0"

url = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=csv&gid={GID}"

class_df = pl.read_csv(url)
class_df

shape: (84, 4)
┌──────────────┬──────────────────┬─────────────────────────────┬────────────┐
│ state        ┆ name             ┆ page                        ┆ party      │
│ ---          ┆ ---              ┆ ---                         ┆ ---        │
│ str          ┆ str              ┆ str                         ┆ str        │
╞══════════════╪══════════════════╪═════════════════════════════╪════════════╡
│ Alabama      ┆ Tommy Tuberville ┆ Tommy_Tuberville            ┆ Republican │
│ Alabama      ┆ Katie Britt      ┆ Katie_Britt                 ┆ Republican │
│ Alaska       ┆ Lisa Murkowski   ┆ Lisa_Murkowski              ┆ Republican │
│ Alaska       ┆ Dan Sullivan     ┆ Dan_Sullivan_(U.S._senator) ┆ Republican │
│ Arizona      ┆ Mark Kelly       ┆ Mark_Kelly                  ┆ Democratic │
│ …            ┆ …                ┆ …                           ┆ …          │
│ South Dakota ┆ John Thune       ┆ John_Thune                  ┆ Republican │
│ Tennessee    ┆ Marsha Blackburn ┆ Marsha_Blackburn            ┆ Republican │
│ Tennessee    ┆ Bill Hagerty     ┆ Bill_Hagerty                ┆ Republican │
│ Texas        ┆ John Cornyn      ┆ John_Cornyn                 ┆ Republican │
│ Texas        ┆ Ted Cruz         ┆ Ted_Cruz                    ┆ Republican │
└──────────────┴──────────────────┴─────────────────────────────┴────────────┘

Then, we can cycle through the rows of the dataset, putting together the Wikipedia data from each row, and then create a corpus object.

In [26]:

wiki_df = []
for row in class_df.iter_rows(named=True):
    wiki_df.append(pl.DataFrame({
        "doc_id": row['name'],
        "text": wiki_get_text(row['page'])
    }))

wiki_df = pl.concat(wiki_df)
wiki_df

shape: (84, 2)
┌──────────────────┬───────────────────────────────────────────────────────────────────────────────┐
│ doc_id           ┆ text                                                                          │
│ ---              ┆ ---                                                                           │
│ str              ┆ str                                                                           │
╞══════════════════╪═══════════════════════════════════════════════════════════════════════════════╡
│ Tommy Tuberville ┆ Thomas Hawley Tuberville (/ˈtʌbərvɪl/; TUH-bərv-il; born September 18, 1954)  │
│                  ┆ is an American politician, and retired college football coach and sports      │
│                  ┆ broadcaster who is the senior United States senator from Alabama, a seat he   │
│                  ┆ has held since 2021. He is a member of the Republican Party. Before entering  │
│                  ┆ politics, Tuberville was the head football coach at Auburn University from    │
│                  ┆ 1999 to 2008. He was also the head football coach at the University of        │
│                  ┆ Mississippi from 1995 to 1998, Texas Tech University from 2010 to 2012, and   │
│                  ┆ the University of Cincinnati from 2013 to 2016. Tuberville won five national  │
│                  ┆ coach-of-the-year awards (AP, AFCA, Sporting News, Walter Camp, and Bear      │
│                  ┆ Bryant) after Auburn's 13–0 season in 2004, in which Auburn won the           │
│                  ┆ Southeastern Conference title and the Sugar Bowl, but was left out of the BCS │
│                  ┆ National Championship Game. He earned his 100th career win in 2007.           │
│                  ┆ Tuberville is the only Auburn football coach to beat in-state rival Alabama   │
│                  ┆ six consecutive times. In 2015, he…                                           │
│ Katie Britt      ┆ Katie Elizabeth Boyd Britt (née Boyd; born February 2, 1982) is an American   │
│                  ┆ politician and attorney serving since 2023 as the junior United States        │
│                  ┆ senator from Alabama. A member of the Republican Party, Britt is the first    │
│                  ┆ woman to be elected to the U.S. Senate from Alabama and the youngest          │
│                  ┆ Republican woman to be elected to the Senate. She was president and CEO of    │
│                  ┆ the Business Council of Alabama from 2019 to 2021, and served as chief of     │
│                  ┆ staff for the previous incumbent, Richard Shelby, from 2016 to 2018. Britt    │
│                  ┆ was born Katie Elizabeth Boyd on February 2, 1982, to Julian and Debra Boyd   │
│                  ┆ in Enterprise, Alabama. During her youth she worked at her family's business. │
│                  ┆ Her family lived near Fort Rucker in Dale County, Alabama. Her father owned a │
│                  ┆ hardware store and later a boat dealership; her mother owned a dance studio.  │
│                  ┆ A graduate of Enterprise High School, Britt was a cheerleader and a           │
│                  ┆ valedictorian. After graduating in 2000 she studied political science at the  │
│                  ┆ University of Alabama. She was…                                               │
│ Lisa Murkowski   ┆  Lisa Ann Murkowski (/mərˈkaʊski/                                             │
│                  ┆ mər-KOW-ski; born May 22, 1957) is an American attorney and politician        │
│                  ┆ serving as the senior United States senator from the state of Alaska, having  │
│                  ┆ held the seat since 2002. She is the first woman to represent Alaska in the   │
│                  ┆ U.S. Congress and is the Senate's second-most senior Republican woman.        │
│                  ┆ Murkowski became dean of Alaska's congressional delegation upon               │
│                  ┆ Representative Don Young's death. Murkowski is the daughter of former U.S.    │
│                  ┆ senator and governor of Alaska Frank Murkowski. She was appointed to the      │
│                  ┆ Senate by her father, who resigned his seat in 2002 to become Alaska's        │
│                  ┆ governor. Murkowski became the first Alaskan-born member of Congress and      │
│                  ┆ completed her father's unexpired Senate term, which ended in January 2005.    │
│                  ┆ Before her appointment to the Senate, she had been a member of the Alaska     │
│                  ┆ House of Representatives since 1999. Murkowski ran for and won a full term in │
│                  ┆ 2004 with 48% of the vote. After losing the 2010 Republican primary to Tea    │
│                  ┆ Party candida…                                                                │
│ Dan Sullivan     ┆ Daniel Scott Sullivan (born November 13, 1964) is an American politician,     │
│                  ┆ attorney, and Marine Corps veteran serving as the junior United States        │
│                  ┆ senator from the state of Alaska since 2015. A member of the Republican       │
│                  ┆ Party, Sullivan previously served as the commissioner of the Alaska           │
│                  ┆ Department of Natural Resources from 2010 to 2013, and as the Alaska Attorney │
│                  ┆ General from 2009 to 2010. Sullivan grew up in a suburb of Cleveland, Ohio    │
│                  ┆ and graduated from Culver Academies in Indiana. He studied economics at       │
│                  ┆ Harvard University, then earned joint foreign service and Juris Doctor        │
│                  ┆ degrees from Georgetown University. He was on active duty for the United      │
│                  ┆ States Marine Corps from 1993 to 1997, 2004 to 2006, and in 2009 and 2013.    │
│                  ┆ Between 1997 and 1999, he clerked for judges on the United States Court of    │
│                  ┆ Appeals for the Ninth Circuit and the Alaska Supreme Court. He worked as an   │
│                  ┆ attorney in private practice in Anchorage, Alaska, from 2000 to 2002.         │
│                  ┆ Sullivan moved to Washington, DC to work for the …                            │
│ Mark Kelly       ┆ Mark Edward Kelly (born February 21, 1964) is an American politician and a    │
│                  ┆ retired astronaut and naval officer. He is the senior United States senator   │
│                  ┆ from Arizona, a seat he has held since 2020. He is a member of the Democratic │
│                  ┆ Party. Kelly flew combat missions during the Gulf War as a naval aviator      │
│                  ┆ before being selected as a NASA Space Shuttle pilot in 1996. His identical    │
│                  ┆ twin brother, Scott Kelly, also became a NASA astronaut that year. Mark flew  │
│                  ┆ his first space mission in 2001 as pilot of STS-108, then piloted STS-121 in  │
│                  ┆ 2006, and commanded STS-124 in 2008 and STS-134 (the final mission of Space   │
│                  ┆ Shuttle Endeavour) in 2011. In January 2011, Kelly's wife, then-Arizona       │
│                  ┆ Representative Gabby Giffords, was shot and nearly killed in an assassination │
│                  ┆ attempt in Arizona. Kelly retired from the Navy and NASA that October. In     │
│                  ┆ 2013, Kelly and Giffords founded a nonprofit political action committee,      │
│                  ┆ Americans for Responsible Solutions (later merged into Giffords), which       │
│                  ┆ campaigned for gun cont…                                                      │
│ …                ┆ …                                                                             │
│ John Thune       ┆ John Randolph Thune (/θuːn/ THOON; born January 7, 1961) is an American       │
│                  ┆ politician serving as the senior United States senator from South Dakota, a   │
│                  ┆ seat he has held since 2005. From 1997 to 2003, he was the U.S.               │
│                  ┆ representative for South Dakota's at-large congressional district. A          │
│                  ┆ Republican, Thune has been the Senate majority leader and Senate Republican   │
│                  ┆ leader since January 2025. A South Dakota native, Thune is a graduate of      │
│                  ┆ Biola University and the University of South Dakota. He was elected to the    │
│                  ┆ House of Representatives in 1996 and reelected in 1998 and 2000. He first ran │
│                  ┆ for the U.S. Senate in 2002, narrowly losing to incumbent senator Tim         │
│                  ┆ Johnson. In 2004, Thune ran for Senate again and defeated Senate Democratic   │
│                  ┆ leader Tom Daschle, making Daschle the first incumbent Senate leader to lose  │
│                  ┆ an election since 1952. During his Senate tenure, Thune has served as the     │
│                  ┆ Republican chief deputy whip (2007–2009); chair of the Senate Republican      │
│                  ┆ Policy Committee (2009–2012); Senate Republica…                               │
│ Marsha Blackburn ┆ Mary Marsha Blackburn (née Wedgeworth; born June 6, 1952) is an American      │
│                  ┆ politician and businesswoman serving as the senior United States senator from │
│                  ┆ Tennessee. Blackburn was first elected to the Senate in 2018. A member of the │
│                  ┆ Republican Party, Blackburn was a state senator from 1999 to 2003 and         │
│                  ┆ represented Tennessee's 7th congressional district in the United States House │
│                  ┆ of Representatives from 2003 to 2019, during which time the National Journal  │
│                  ┆ rated her among the House's most conservative members. A supporter of the Tea │
│                  ┆ Party movement, Blackburn is a staunch ally of President Donald Trump. She    │
│                  ┆ opposes abortion, same-sex marriage, and the Affordable Care Act. On November │
│                  ┆ 6, 2018, Blackburn became the first woman to be elected to the U.S. Senate    │
│                  ┆ from Tennessee, defeating Democratic former Tennessee Governor Phil Bredesen. │
│                  ┆ Blackburn became the state's senior senator in January 2021 upon the          │
│                  ┆ retirement of Senator Lamar Alexander. Upon the retirement of Congressman Jim │
│                  ┆ Cooper in 2023…                                                               │
│ Bill Hagerty     ┆ William Francis  Hagerty IV (/ˈhæɡərti/ HAG-ər-tee; born August 14, 1959) is  │
│                  ┆ an American politician, businessman, and diplomat serving as the junior       │
│                  ┆ United States senator from Tennessee since 2021. A member of the Republican   │
│                  ┆ Party, he served as the 30th United States ambassador to Japan from 2017 to   │
│                  ┆ 2019 under President Donald Trump. Hagerty began his career in private        │
│                  ┆ equity. Hagerty is the co-founder of Hagerty Peterson & Company, a private    │
│                  ┆ equity investment firm; he is a former managing director of the firm. From    │
│                  ┆ 2011 to 2014, Hagerty served as commissioner of the Tennessee Department of   │
│                  ┆ Economic and Community Development. He led a successful effort to bring a     │
│                  ┆ Major League Soccer franchise to Nashville. President Trump nominated Hagerty │
│                  ┆ to serve as U.S. ambassador to Japan on March 27, 2017; the U.S. Senate       │
│                  ┆ confirmed him on July 13 in an 86–12 vote. Hagerty was sworn in as the 30th   │
│                  ┆ United States ambassador to Japan on July 27, 2017. He resigned in July 2019  │
│                  ┆ to run for the U.S. Sena…                                                     │
│ John Cornyn      ┆ John Cornyn III (/ˈkɔːrnɪn/ KOR-nin; born February 2, 1952) is an American    │
│                  ┆ politician serving as the senior United States senator from Texas, a seat he  │
│                  ┆ has held since 2002. He is a member of the Republican Party. Born in Houston, │
│                  ┆ Cornyn is a graduate of Trinity University, St. Mary's University School of   │
│                  ┆ Law, and the University of Virginia School of Law. He was a judge on Texas's  │
│                  ┆ 37th District Court from 1985 to 1991, an associate justice of the Texas      │
│                  ┆ Supreme Court from 1991 to 1997, and Attorney General of Texas from 1999 to   │
│                  ┆ 2002. He was first elected to the U.S. Senate in 2002. During his tenure,     │
│                  ┆ Cornyn chaired the National Republican Senatorial Committee from 2009 to 2013 │
│                  ┆ and served as the Senate Republican whip from 2013 to 2019. Cornyn was born   │
│                  ┆ in Houston, the second child of Atholene Gale Cornyn (née Danley) and John    │
│                  ┆ Cornyn II, a colonel in the U.S. Air Force. He attended the American School   │
│                  ┆ in Japan after his family moved to Tokyo in 1968, and graduated from it in    │
│                  ┆ 1969. In 1973…                                                                │
│ Ted Cruz         ┆ Rafael Edward  Cruz (/kruːz/; born December 22, 1970) is an American          │
│                  ┆ politician and attorney serving as the junior United States senator from      │
│                  ┆ Texas since 2013. A member of the Republican Party, Cruz was the solicitor    │
│                  ┆ general of Texas from 2003 to 2008. Since 2025, Cruz has chaired the Senate   │
│                  ┆ Commerce Committee. After graduating from Princeton University with a         │
│                  ┆ Bachelor of Arts and earning a Juris Doctor from Harvard Law School, Cruz     │
│                  ┆ pursued a career in politics, eventually serving as a policy advisor in the   │
│                  ┆ George W. Bush administration. In 2003, Texas attorney general Greg Abbott    │
│                  ┆ appointed Cruz to serve as Solicitor General, a position he held until 2008.  │
│                  ┆ Cruz was elected to the U.S. Senate in 2012, becoming the first Hispanic      │
│                  ┆ American to serve as a U.S. senator from Texas. In the Senate, he has taken   │
│                  ┆ consistently conservative positions on economic and social policy. He played  │
│                  ┆ a leading role in the 2013 federal government shutdown, unsuccessfully        │
│                  ┆ seeking to force Congress and Preside…                                        │
└──────────────────┴───────────────────────────────────────────────────────────────────────────────┘

As before, we will next create an annotation object.

In [27]:
anno = DSText.process(wiki_df, nlp)
anno

shape: (405_545, 15)
┌──────────────────┬─────┬─────┬────────────┬───┬──────────┬──────────┬──────────┬─────────┐
│ doc_id           ┆ sid ┆ tid ┆ token      ┆ … ┆ dep      ┆ head_idx ┆ ent_type ┆ ent_iob │
│ ---              ┆ --- ┆ --- ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---     │
│ str              ┆ i64 ┆ i64 ┆ str        ┆   ┆ str      ┆ i64      ┆ str      ┆ str     │
╞══════════════════╪═════╪═════╪════════════╪═══╪══════════╪══════════╪══════════╪═════════╡
│ Tommy Tuberville ┆ 1   ┆ 1   ┆            ┆ … ┆ dep      ┆ 2        ┆          ┆ O       │
│ Tommy Tuberville ┆ 1   ┆ 2   ┆ Thomas     ┆ … ┆ compound ┆ 4        ┆ PERSON   ┆ B       │
│ Tommy Tuberville ┆ 1   ┆ 3   ┆ Hawley     ┆ … ┆ compound ┆ 4        ┆ PERSON   ┆ I       │
│ Tommy Tuberville ┆ 1   ┆ 4   ┆ Tuberville ┆ … ┆ nsubj    ┆ 14       ┆ PERSON   ┆ I       │
│ Tommy Tuberville ┆ 1   ┆ 5   ┆ (          ┆ … ┆ punct    ┆ 4        ┆          ┆ O       │
│ …                ┆ …   ┆ …   ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …       │
│ Ted Cruz         ┆ 470 ┆ 10  ┆ comedy     ┆ … ┆ compound ┆ 11       ┆          ┆ O       │
│ Ted Cruz         ┆ 470 ┆ 11  ┆ film       ┆ … ┆ compound ┆ 13       ┆          ┆ O       │
│ Ted Cruz         ┆ 470 ┆ 12  ┆ Lady       ┆ … ┆ compound ┆ 13       ┆ PERSON   ┆ B       │
│ Ted Cruz         ┆ 470 ┆ 13  ┆ Ballers    ┆ … ┆ pobj     ┆ 6        ┆ PERSON   ┆ I       │
│ Ted Cruz         ┆ 470 ┆ 14  ┆ .          ┆ … ┆ punct    ┆ 5        ┆          ┆ O       │
└──────────────────┴─────┴─────┴────────────┴───┴──────────┴──────────┴──────────┴─────────┘

3. Adapting the code show in the text, find the 8 nouns that are the most common on each page and print out the results to have a summary of the themes of each page. What patterns do you see? Are there any challenges? What else might you want to do with this data?

In [28]:
(
    anno
    .filter(c.upos == "NOUN")
    .group_by(c.doc_id, c.lemma)
    .agg(count = pl.len())
    .sort(c.doc_id, c.count, descending=[False, True])
    .group_by(c.doc_id)
    .head(8)
    .group_by(c.doc_id)
    .agg(top_adj = c.lemma.sort().str.join("; "))
)

shape: (82, 2)
┌────────────────────┬──────────────────────────────────────────────────────────────────────────┐
│ doc_id             ┆ top_adj                                                                  │
│ ---                ┆ ---                                                                      │
│ str                ┆ str                                                                      │
╞════════════════════╪══════════════════════════════════════════════════════════════════════════╡
│ Gary Peters        ┆ %; bill; campaign; district; election; member; senator; state            │
│ Tina Smith         ┆ %; administration; campaign; election; letter; president; senator; state │
│ Bill Cassidy       ┆ %; bill; cassidy; child; election; health; legislation; vote             │
│ Maggie Hassan      ┆ %; bill; campaign; governor; law; senator; state; year                   │
│ Cindy Hyde-Smith   ┆ %; bill; election; office; senator; state; time; vote                    │
│ …                  ┆ …                                                                        │
│ Lisa Murkowski     ┆ %; campaign; election; father; seat; senator; time; vote                 │
│ Richard Blumenthal ┆ attorney; law; letter; member; senator; service; state; year             │
│ John Thune         ┆ %; election; leader; race; senator; vote; whip; year                     │
│ Mark Kelly         ┆ crew; day; election; gun; mission; space; time; wife                     │
│ Ruben Gallego      ┆ %; campaign; election; group; member; organization; state; vote          │
└────────────────────┴──────────────────────────────────────────────────────────────────────────┘